"""
One-time script to fetch all Santa Maria category names from the live site
and dump them as cPath=name pairs for use in the postprocessor data file.

Run from project root:
    python analysis/santamaria/fetch_categories.py

Output: one line per category — "1_117=GALLETITAS" — written to stdout.
Redirect to: scraper/postprocess/data/santamaria_categories.txt
"""

import asyncio
import os
import re
import sys
import warnings

import httpx
from bs4 import BeautifulSoup
from dotenv import load_dotenv

load_dotenv()
warnings.filterwarnings("ignore", message="Unverified HTTPS request")
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BASE = "https://tienda.santamariasa.com.ar/comercio"


async def login(client: httpx.AsyncClient) -> None:
    r = await client.get(f"{BASE}/login.php")
    soup = BeautifulSoup(r.text, "lxml")
    formid_el = soup.select_one('input[name="formid"]')
    if not formid_el:
        raise RuntimeError("formid CSRF token not found")
    payload = {
        "formid":        formid_el["value"],
        "email_address": os.getenv("SANTAMARIA_USER"),
        "password":      os.getenv("SANTAMARIA_PASS"),
    }
    resp = await client.post(f"{BASE}/login.php?action=process", data=payload)
    if "login.php" in str(resp.url):
        raise RuntimeError("Login failed")
    print("# Logged in", file=sys.stderr)


def _clean_cpath(href: str) -> str | None:
    """Extract cPath value from href, strip osCsid, return None if not cPath URL."""
    m = re.search(r"cPath=([\d_]+)", href)
    return m.group(1) if m else None


async def run() -> None:
    categories: dict[str, str] = {}

    async with httpx.AsyncClient(verify=False, follow_redirects=True) as client:
        await login(client)

        # Step 1: fetch homepage — get top-level categories (cPath=N, single int)
        r = await client.get(f"{BASE}/index.php")
        soup = BeautifulSoup(r.text, "lxml")

        top_links: list[tuple[str, str]] = []  # (cpath, url)
        for a in soup.select("a[href*='cPath=']"):
            href = a.get("href", "")
            cpath = _clean_cpath(href)
            if not cpath or "_" in cpath:
                continue  # skip leaf links
            name = a.get_text(strip=True)
            if not name or cpath in categories:
                continue
            full = href if href.startswith("http") else f"{BASE}/{href.lstrip('/')}"
            full = re.sub(r"[&?]?osCsid=[^&]*", "", full).strip("&?")
            categories[cpath] = name.upper()
            top_links.append((cpath, full))

        print(f"# Found {len(top_links)} top-level categories", file=sys.stderr)

        # Step 2: visit each top-level page — collect leaf categories (cPath=N_M)
        for top_cpath, top_url in sorted(top_links):
            await asyncio.sleep(0.3)
            try:
                r = await client.get(top_url)
                soup = BeautifulSoup(r.text, "lxml")
            except httpx.HTTPError as e:
                print(f"# ERROR {top_url}: {e}", file=sys.stderr)
                continue

            for a in soup.select("a[href*='cPath=']"):
                href = a.get("href", "")
                cpath = _clean_cpath(href)
                if not cpath or "_" not in cpath:
                    continue  # skip top-level links
                name = a.get_text(strip=True)
                if not name:
                    continue
                if cpath not in categories:
                    categories[cpath] = name.upper()

        print(f"# Total categories: {len(categories)}", file=sys.stderr)

    # Emit sorted output
    print("# Santa Maria category mapping: cPath=NAME")
    print("# Generated by analysis/santamaria/fetch_categories.py")
    print("# Format: cPath=CANONICAL_NAME")
    print()
    for cpath in sorted(categories, key=lambda x: [int(p) for p in x.split("_")]):
        print(f"{cpath}={categories[cpath]}")


asyncio.run(run())
